import { tableSlotRecipe } from "./table";

export const slotRecipes = {
  //   accordion: accordionSlotRecipe,
  //   actionBar: actionBarSlotRecipe,
  //   alert: alertSlotRecipe,
  //   avatar: avatarSlotRecipe,
  //   blockquote: blockquoteSlotRecipe,
  //   breadcrumb: breadcrumbSlotRecipe,
  //   card: cardSlotRecipe,
  //   checkbox: checkboxSlotRecipe,
  //   checkboxCard: checkboxCardSlotRecipe,
  //   collapsible: collapsibleSlotRecipe,
  //   dataList: dataListSlotRecipe,
  //   dialog: dialogSlotRecipe,
  //   drawer: drawerSlotRecipe,
  //   editable: editableSlotRecipe,
  //   emptyState: emptyStateSlotRecipe,
  //   field: fieldSlotRecipe,
  //   fieldset: fieldsetSlotRecipe,
  //   fileUpload: fileUploadSlotRecipe,
  //   hoverCard: hoverCardSlotRecipe,
  //   list: listSlotRecipe,
  //   menu: menuSlotRecipe,
  //   nativeSelect: nativeSelectSlotRecipe,
  //   numberInput: numberInputSlotRecipe,
  //   pinInput: pinInputSlotRecipe,
  //   popover: popoverSlotRecipe,
  //   progress: progressSlotRecipe,
  //   progressCircle: progressCircleSlotRecipe,
  //   radioCard: radioCardSlotRecipe,
  //   radioGroup: radioGroupSlotRecipe,
  //   ratingGroup: ratingGroupSlotRecipe,
  //   segmentGroup: segmentGroupSlotRecipe,
  //   select: selectSlotRecipe,
  //   slider: sliderSlotRecipe,
  //   stat: statSlotRecipe,
  //   steps: stepsSlotRecipe,
  //   switch: switchSlotRecipe,
  table: tableSlotRecipe,
  //   tabs: tabsSlotRecipe,
  //   tag: tagSlotRecipe,
  //   toast: toastSlotRecipe,
  //   tooltip: tooltipSlotRecipe,
  //   status: statusSlotRecipe,
  //   timeline: timelineSlotRecipe,
  //   colorPicker: colorPickerSlotRecipe,
  //   qrCode: qrCodeSlotRecipe,
};
